version: '3'

tasks:
  start:
    cmds:
      - richgo run ./cmd
  start-dev:
    cmds:
      - reflex -r '\.go$' -d none -s -- sh -c 'clear && richgo run ./cmd'

  test-dev:
    cmds:
      - task test_migrateup
      - reflex -r '\_test.go' -d none -s -- sh -c 'richgo test -v -cover -coverprofile=c.out ./db/sqlc/...'

  test-covarage:
    cmds:
      - task test_migrateup
      - go tool cover -html=c.out


  test_migrateup:
    cmds:
      - migrate -path ./db/migrations -database "postgresql://root:password_test@0.0.0.0:5432/simple_bank_test?sslmode=disable" -verbose up

  test_migratedown:
    cmds:
      - migrate -path ./db/migrations -database "postgresql://root:password_test@0.0.0.0:5432/simple_bank_test?sslmode=disable" -verbose down

  migrateup:
    cmds:
      - migrate -path ./db/migrations -database "postgresql://root:password@0.0.0.0:5432/simple_bank?sslmode=disable" -verbose up

  migratedown:
    cmds:
      - migrate -path ./db/migrations -database "postgresql://root:password@0.0.0.0:5432/simple_bank?sslmode=disable" -verbose down

  sqlc:
    cmds:
      - sqlc generate
    
